---
- name: "update apt repo"
  become: true
  apt:
    update_cache: yes

- name: "upgrade apt packages"
  become: true
  apt:
    upgrade: yes

- name: "remove dependencies that are no longer required"
  become: true
  apt:
    autoremove: yes

- name: "install dependencies (nodejs and npm)"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Create backend app directory
  file:
    path: ~/backend_app_dir
    state: directory

- name: "Copy artifact into instance"
  become: true
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend_app_dir/artifact.tar.gz

- name: "Start app"
  become: true
  shell: |
    cd /home/ubuntu/backend_app_dir
    tar xzvf artifact.tar.gz
    npm install
    npm run build
    pm2 stop default
    pm2 start main.js
  register: execute_node
  
- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"
    
- name: "Configure pm2 to start as service"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save